apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelmemorybackend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TravelMemory-backend
  template:
    metadata:
      labels:
        app: TravelMemory-backend
    spec:
      containers:
      - name: travelmemorybackend
        image: sukhilnair/jenkins-class:backend-11
        env:
        - name: MONGO_URI
          valueFrom: 
            secretKeyRef:
              name: backend-secret
              key: MONGO_URI
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001
