apiVersion: v1
kind: Service
metadata:
  name: travelmemorybackend
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: TravelMemory-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001